ktor:
    application:
        modules:
            - com.crezent.finalyearproject.ApplicationKt.module
    deployment:
      port: 8080
      host: 172.20.10.12  #Will comment when pushing
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "UI Wallet Server"
  issuer: "ktor server"

