ktor:
    application:
        modules:
            - com.crezent.finalyearproject.ApplicationKt.module
    deployment:
      port: 8080
      host: "192.168.38.175"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "UI Wallet Server"
  issuer: "ktor server"

